#!/bin/sh

# To enable this hook place it in .git/hooks.
#
# If you're using worktrees in the way I do, place it in .bare/hooks

# Path to the file where the issue number is stored
ISSUE_FILE=~/.gitnum_env

# Check if the issue file exists and is not empty
if [ -f "$ISSUE_FILE" ] && [ -s "$ISSUE_FILE" ]; then
   # Read the issue number
   issue_number=$(cat "$ISSUE_FILE")

   # Check the branch name for a 3 to 9 digit number (an issue number).
   ISSUE_NUMBER=`echo "$issue_number" | egrep -o '[0-9]{3,9}'`

   # If branch contains a match for an issue number prepend the commit
   # message with '#<issue_number> <commit message>.
   if [ -n "$ISSUE_NUMBER" ] 
   then
      sed -i.bak -e "1s/^/#$ISSUE_NUMBER: \n /" "$GIT_DIR/COMMIT_EDITMSG"
   fi
fi

