#!/usr/bin/env zsh
export STOW_FOLDERS="config,git,gitmux,tmux,wezterm,zsh"

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
done
popd

ln -s ~/.dotfiles/git/.gitignore ~/.gitignore
