#!/usr/bin/env zsh
export STOW_FOLDERS="config,git,gitmux,tmux,warp,wezterm,zsh"

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
done
popd

ln -s ~/.dotfiles/git/.gitignore ~/.gitignore

# pi coding agent
mkdir -p ~/.pi/agent
ln -sf ~/.config/pi/agent/settings.json ~/.pi/agent/settings.json
ln -sf ~/.config/pi/agent/skills ~/.pi/agent/skills
ln -sf ~/.config/pi/agent/extensions ~/.pi/agent/extensions
ln -sf ~/.config/pi/agent/keybindings.json ~/.pi/agent/keybindings.json
