"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Dan Susman"
email = "frenchminister@gmail.com"

[ui]
editor = "nvim"
default-command = "log"

[colors]
"diff token" = { reverse = true, underline = false }

# disable pagination for `jj status`
[[--scope]]
--when.commands = ["status", "log"]
[--scope.ui]
paginate = "never"

