# Lazygit configuration with Claude AI commit integration

customCommands:
  - key: R
    context: commits
    command: git commit --allow-empty --amend --no-verify
    output: terminal
  - key: '<c-k>' # Ctrl+K for AI commit
    context: 'global'
    description: 'Generate AI commit message'
    command: 'generate-commit | git commit -F -'
    loadingText: 'Generating commit message with Claude...'
    output: log
# Optional: Configure git editor to use the generated message
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  commit:
    autoWrapCommitMessage: false
gui:
  showIcons: true
  sidePanelWidth: 0.3333
